name: Publish to Nuget

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore     
      - name: Test
        run: |
          dotnet test     
      - name: Publish EF6
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
            PROJECT_FILE_PATH: src/Unosquare.EntityFramework.Specification.EF6/Unosquare.EntityFramework.Specification.EF6.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish EFCore
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
            PROJECT_FILE_PATH: src/Unosquare.EntityFramework.Specification.EFCore/Unosquare.EntityFramework.Specification.EFCore.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}